### ISSUE TITLE
Friend object has no uuid in Player.friends.records

### ISSUE THREAD

**Issue by Neefs** [Preocts/hyapi#8]
```py
def main():
    ign = input('Please enter your ign: ')
    uuid = UUIDLookup().resolve_by_name(ign).id
    if not uuid:
        print("That player was not found. Restarting")
        return main()
    player = Player()
    player.fetch_player(uuid)
    print(player.friends.records)
```
This is my code when I print the records its a list of Friend objects that have no uuidsender and uuidreceiver. I can get both of those using raw_data. Output in file.
[output.txt](https://github.com/Preocts/hyapi/files/7611000/output.txt)

**Comment by Preocts** [comment]
I expect the cause is simply an incorrect key name here:
https://github.com/Preocts/hyapi/blob/main/src/hyapi/models/playerfriends.py#L22-L23

I can look into it this weekend. Also open to a pr for updating those key names if your `raw_data` confirms that is the issue.

**Comment by Preocts** [comment]
Yeah, those names should be camelCase.  `uuidSender` and `uuidReceiver`
https://api.hypixel.net/#tag/Player-Data/paths/~1player/get

**Comment by Preocts** [comment]
Thanks!
